"""fix field date

Revision ID: f0b7ad62828b
Revises: 2ce5c84d86c4
Create Date: 2024-11-26 06:24:06.454661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0b7ad62828b"
down_revision: Union[str, None] = "2ce5c84d86c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("date", sa.Date(), nullable=False))
    op.drop_column("products", "sales_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("sales_data", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("products", "date")
    # ### end Alembic commands ###
